services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///database.db
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
